### ISSUE TITLE
guardian.co.uk is not intercepted for me

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#15]
in fact most of the sites that i'm trying to block can't be intercepted. 
i get this in the javascript console: 

`Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://mir.lu" from accessing a cross-origin frame.`

**Comment by rowanvb** [comment]
we're currently working on resolving this issue.
we will keep you posted!

**Comment by Mantsje** [comment]
As of today these problems should be fixed. We are glad to state that we have not been able to find a valid url that does not work for us at this point. Besides a few (known) edge cases that is, we are working on filtering those out to get the optimal experience as MVP

**Comment by mircealungu** [comment]
Looking forward to testing this then!
