### ISSUE TITLE
Slider in options page calls chrome.sync.storage too often.

### ISSUE THREAD

**Issue by spazzy** [RUGSoftEng/2017-The-Distraction-Shield#23]
This method is called every "tick" of changing the slider.
A call is made to chrome.sync.storage every call. This makes us exceed the chrome.sync.storage call amount limit.
So maybe this method should only be called after pressing a "save" button, or only after 2 seconds of no changes.

method name: initIntervalSlider
file: sampleExtension/optionsPage/htmlFunctionality.js
line: 81

**Comment by rowanvb** [comment]
fixed
