### ISSUE TITLE
TDS redirects me to the login page

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#46]
i'm trying the code on the release-1.1.0 branch. is there a branch where the login to TDS is not needed anymore? or do you guys wait for some changes on our side before you can implement this? I'm notifying @martinavagyan here, so he is aware of the discussion.

**Comment by pieterDekker** [comment]
we are indeed waiting for Zeeguu to not require sessionID anymore, however i completely forgot to ask for a status update, i will do that now.

**Comment by mircealungu** [comment]
good point!
zeeguu does not need a sessionID anymore.
