### ISSUE TITLE
inconsistent terminology: save / disable blocking

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#47]
<img width="274" alt="screenshot 2017-05-02 19 54 09" src="https://cloud.githubusercontent.com/assets/464519/25632074/9ef9b428-2f72-11e7-9baa-fc06dbf41829.png">
<img width="277" alt="screenshot 2017-05-02 19 54 00" src="https://cloud.githubusercontent.com/assets/464519/25632075/9f041706-2f72-11e7-96f4-62086ea7ecf3.png">

**Comment by erikiej1** [comment]
Changed to "block" and "unblock"
