### ISSUE TITLE
UI Design: focus of attention is attracted to irrelevant part of page

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#50]
My focus of attention is attracted to the big blue blob of color on the page where there is... nothing important to be conveyed with that message . Can we redesign this to make it less strident?

<img width="813" alt="screenshot 2017-05-03 12 02 42" src="https://cloud.githubusercontent.com/assets/464519/25656275/8d12712e-2ff8-11e7-88b2-fbb4faae3a52.png">

**Comment by erikiej1** [comment]
the big blue blob now contains the name of the extension.
