### ISSUE TITLE
Interception message style should be improved

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#52]
The space for the interception message is not used well enough. Blue bar attracts the attention too much, and the white rectangle is larger than needed. Also in this particular case, left aligned text does not seem to function that well. 

![screenshot 2017-05-03 12 45 21](https://cloud.githubusercontent.com/assets/464519/25657916/79411206-3000-11e7-8430-547a4f95a185.png)

The general idea of a design that I would want is: 

<img width="1110" alt="screenshot 2017-05-03 12 58 10" src="https://cloud.githubusercontent.com/assets/464519/25657896/68b9fec0-3000-11e7-8dd3-89646ddc8543.png">

Or maybe the message could also be at the bottom? 
<img width="1108" alt="screenshot 2017-05-03 12 55 28" src="https://cloud.githubusercontent.com/assets/464519/25657924/874ab000-3000-11e7-9cd8-dac3355bdc17.png">

**Comment by erikiej1** [comment]
I took the design with the panel in the bottom. Also added the logo. To my knowledge, we cannot inject an image, so I uploaded one to imageschack as a temporary solution. It would be better if we did not show the logo or if we got it from the zeegu website...

**Comment by mircealungu** [comment]
Cool! I've uploaded the aikido-elephant on the zeeguu site: 
https://www.zeeguu.unibe.ch/static/img/aikido-elephant.png
