### ISSUE TITLE
terminology to choose: block vs. intercept

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#55]
Here we have in the same options page both of them:
- **websites** you should be *intercepted* from
- enter the **site** you want to *block*

I'm not sure which is better, i tend to think intercept is more expressive for what we do but it's also longer. It should also be the same term that's being used in the menu.

<img width="802" alt="screenshot 2017-05-04 19 13 09" src="https://cloud.githubusercontent.com/assets/464519/25716003/cebbe1a4-30fd-11e7-951b-67623df11000.png">

**Comment by erikiej1** [comment]
Changed text in options page to "Websites that should be blocked"
