### ISSUE TITLE
detecting that the extension was already installed

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#62]
so we don't invite the user to read the guide again, in case only an update has been installed. 

instead, it's probably better to be quiet, or at most show a message with release notes. although, this could be better in the options, as another link i'd say. 

can you check if this is possible? and if so, make it happen? 

thanks!

**Comment by rowanvb** [comment]
https://developer.chrome.com/extensions/runtime#event-onInstalled

This is exactly when we start the introTour.
However I was unable to find any documentation on unpacked extensions and reloading the extension page. 

_Fired when the extension is **first** installed_ 
This however is exactly what you mentioned.
