### ISSUE TITLE
i see the interception message on the wrong page

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#63]
for me it appears on this page:

   https://www.zeeguu.unibe.ch/practice/

![screenshot 2017-05-21 14 40 33](https://cloud.githubusercontent.com/assets/464519/26284093/8f65b5dc-3e33-11e7-86b6-6a869c151c3f.png)

can you replicate?

**Comment by pieterDekker** [comment]
I can, now solved in branch ES6
