### ISSUE TITLE
message box should be anchored at the bottom of the window

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#64]
it is too close to the exercises now. the exercises should be alone in the center of the window and the DS note should not distract from the exercises. 

consider using a fixed-position div that is anchored to the bottom of the screen. e.g. http://stackoverflow.com/questions/31942227/stick-div-to-bottom-of-browser-window

or this fiddle: http://jsfiddle.net/uw8f9/

thanks!

**Comment by rowanvb** [comment]
As discussed during the meeting, this issue has been fixed as of today.
