### ISSUE TITLE
after zeeguu login no exercise

### ISSUE THREAD

**Issue by pieterDekker** [RUGSoftEng/2017-The-Distraction-Shield#65]
@mircealungu @martinavagyan 
If a user is not logged in and tries to enter a blacklisted site, they are sent to the login page, and then to the zeeguu homepage where they should be sent to the zeeguu exercises

**Comment by martinavagyan** [comment]
@pieterDekker I have fixed the redirection now, @mircealungu I made a pull request for this issue.

**Comment by pieterDekker** [comment]
@mircealungu is this fix live already?

**Comment by pieterDekker** [comment]
I see now that the issue has been fixed. However, now when i log out, i am still redirected to my exercises(they are from my bookmarks), is this expected behaviour?
