### ISSUE TITLE
Saving a page causes error

### ISSUE THREAD

**Issue by dunnkers** [RUGSoftEng/2017-The-Distraction-Shield#67]
## Problem
Apparent in the current ES6 branch. Error thrown when trying to save page.

<img width="896" alt="screen shot 2017-05-24 at 14 24 48" src="https://cloud.githubusercontent.com/assets/744430/26403036/f44c4d16-408c-11e7-9db9-d34ca5fbef5c.png">

## Reproduction
Click the extension button, then try to `Save current page`.

**Comment by pieterDekker** [comment]
Could not reproduce, instead i do get the page saved, but the button shows no confirmation.

**Comment by dunnkers** [comment]
Oops - my HEAD was not in the latest commit (d9b4da1) in `ES6` branch. The tooltip now doesn't produce the error anymore 👌🏻

However, the button does not show a confirmation indeed. I'll create a separate issue for that.
