### ISSUE TITLE
Fix confirmation in tooltip on successfully blocking a site

### ISSUE THREAD

**Issue by dunnkers** [RUGSoftEng/2017-The-Distraction-Shield#68]
As described by @pieterDekker in #67, the button should give some sort of feedback to let the user know the website was successfully added to the blocked site list.

**Comment by rowanvb** [comment]
this functionality already exists, but was broken with ES6, I will have a look at this though. Not sure if @Mantsje had a look at this already.

**Comment by rowanvb** [comment]
fixed in ES6
