### ISSUE TITLE
Zeeguu injection - wrong screen size

### ISSUE THREAD

**Issue by Eli-Ionescu** [RUGSoftEng/2017-The-Distraction-Shield#89]
Upon arrival on the Zeeguu page, the message injected is too big and hides the answer block of the actual exercise. 
<img width="617" alt="careful" src="https://cloud.githubusercontent.com/assets/10388679/26755899/47d5a628-4897-11e7-8412-8e2e6dbfdca6.PNG">

The problem is caused by the size of the screen (13").

**Comment by dunnkers** [comment]
The problem is not the device screen size, but the viewport dimensions. The interception message overlaps the assignment from around 635 pixels height:

![kapture 2017-06-04 at 23 29 56](https://cloud.githubusercontent.com/assets/744430/26765529/e66d2cd4-497d-11e7-8274-3e50695d7c2e.gif)

**Comment by Eli-Ionescu** [comment]
Added a button so the banner can be closed.

Also, changed the minimum size for the options page, so it fits for screens with smaller resolution.
