### ISSUE TITLE
ember-cli as a build tool ✈️

### ISSUE THREAD

**Issue by dunnkers** [RUGSoftEng/2017-The-Distraction-Shield#91]
Currently, we are using [broccolijs](https://github.com/broccolijs/broccoli) as our build tool. We then use Babel for ES6 transpilation and Webpack for bundling. But we obviously want more.

We want live rebuilding and the ability to write acceptance-, unit- and integration tests whilst developing. We want automatic deployments to the chrome webstore with code minification and uglification when shipping our product. I set out to pull in lots of other libraries and tools to solve this, as described in issues #80, #82, #84 and #85. However, upon further investigation, I realized we could use [ember-cli](https://ember-cli.com) for this.

ember-cli is built on [broccolijs](https://github.com/broccolijs/broccoli), but is way more extensive. Bringing in this build tool would automatically solve all 4 issues at once. 😻 Even though ember-cli is actually made for use with the [emberjs](https://emberjs.com) framework, with some work it can be stripped down to be used with any web project. Some features ember-cli has out of the box:

- Unit, Integration and Acceptance test support using [Testem](https://github.com/testem/testem)
- Fingerprinting production assets (see [here](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark))
- Development server with Live Reload
- [Tree shaking](https://blog.engineyard.com/2016/tree-shaking) to avoid shipping unused code
- Rich [addon ecosystem](https://www.emberaddons.com), allowing us to use an addon for chrome extension deployment, e.g. [ember-cli-deploy-chrome-app](https://github.com/rmachielse/ember-cli-deploy-chrome-app)

I have been working on this in the [`build-step-revolution`](https://github.com/RUGSoftEng/2017-The-Distraction-Shield/tree/build-step-revolution) branch. I will keep you posted in progress in this issue. ✅
- [x] Exclude ember related vendor packages
- [x] Strip down application tree
- [x] Get a page render working
- [x] Have testing work as expected (work around using ember-cli-qunit)
- [x] Merge `Distraction Shield` folder with app folder
- [x] Combine pages with the same extension endpoint (e.g. merge `optionsPage` and `statisticsPage`)
- [x] Split seperate page into addons or place in `/public` folder
- [x] Extract static assets into `/public` folder
- [x] Link css files and let asset pipeline combine them into one
- [x] Build & Test in [chrome://extension](chrome://extensions)

**Comment by dunnkers** [comment]
After thorough of getting ember-cli to work with our folder (e.g. `Distraction Shield` folder and multiple html page), decoupling ember centric functionality turned out too complex. It would take a custom [`application-pipeline`](https://github.com/glimmerjs/glimmer-application-pipeline) and a custom [`resolver`](https://github.com/glimmerjs/glimmer-resolver) to fully decouple the two.

Since we do not use as many third party addons, I've decided to go barebones broccoli anyway.

**Comment by rowanvb** [comment]
Does that mean you're finished?

**Comment by dunnkers** [comment]
Not quite, it means I'm currently extending the Broccoli build pipeline with, among others, [Rollup.js](https://rollupjs.org) to implement all wanted features.
