### ISSUE TITLE
The message box is not functional due to Promise-hell

### ISSUE THREAD

**Issue by Mantsje** [RUGSoftEng/2017-The-Distraction-Shield#93]
The message-box for the options page is at this moment not functional. Due to my lack of knowledge of promises and with that not being capable to make it work again. I'm having the feeling that some things inside the urlFormatter, bockedSiteBuilder and storage contain a little to many promises. Disabling me from catching failing promises at a higher level than where it fails. Please have a look at it, because as of now it is once again not working.

**Comment by dunnkers** [comment]
What branch are you on?
